output   = "my_models"
wipe     = true
no-tests = true
add-enum-types = true

[mysql]
dbname = "playground"
host = "aws-sa-east-1.connect.psdb.cloud"
user = "zz6xx7k2du0x1pjg574o"
pass = "pscale_pw_suL6j7koiDlxFYoedmena6f5Q2XCtJ9N00qHhv1jtjW"