// Code generated by SQLBoiler 4.14.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Account                string
	Example                string
	Exercise               string
	ExerciseModel          string
	Routine                string
	RoutineModel           string
	Session                string
	User                   string
	PrismaMigrations       string
	Classes                string
	CourseAccesses         string
	Courses                string
	Organizations          string
	OrganizationsLibraries string
	OrganizationsMembers   string
}{
	Account:                "Account",
	Example:                "Example",
	Exercise:               "Exercise",
	ExerciseModel:          "ExerciseModel",
	Routine:                "Routine",
	RoutineModel:           "RoutineModel",
	Session:                "Session",
	User:                   "User",
	PrismaMigrations:       "_prisma_migrations",
	Classes:                "classes",
	CourseAccesses:         "course_accesses",
	Courses:                "courses",
	Organizations:          "organizations",
	OrganizationsLibraries: "organizations_libraries",
	OrganizationsMembers:   "organizations_members",
}
